spring:
  data:
    mongodb:
      uri : mongodb+srv://subhamrana:subham@cluster0.j23nlue.mongodb.net/?retryWrites=true&w=majority
      database : Blog
  mail:
    host: smtp.gmail.com
    port: 587
    username: subhamrcf@gmail.com
    password: ilifubjnditkghum
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
